#!/usr/bin/env python3
"""Inline shared chrome (theme.css, theme script, toolbar) into every page.

Why inline rather than <link>/<script src>: every page on this site is a
self-contained HTML file. Readers save them, email them, and print them. An
external asset would break all three. So theme.css is the single source of
truth at author time, and this script bakes it into each page at build time.

    python build_pages.py

Managed regions, each delimited by START/END markers:
  THEME   - token blocks + shared chrome CSS, from theme.css
  SCRIPT  - the head script that resolves the active theme before first paint
  TOOLBAR - the sticky toolbar markup (theme toggle + print)
  TOGGLE  - the click wiring for the toggle and print controls

Idempotent: running twice makes no further change. Tokens a page defines that
theme.css does not own are preserved per mode, so bespoke pages keep extras.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent
THEME = ROOT / "theme.css"

# Generated from _index.template.html, so it is built rather than patched.
GENERATED_INDEX = "index.html"
# Owns an independent token system and is not part of the resources theme.
SKIP = {"vault-navigator.html"}

M = {
    "theme": ("/* THEME:START - generated from theme.css by build_pages.py. Do not edit by hand. */",
              "/* THEME:END */"),
    "script": ("<!-- SCRIPT:START - generated by build_pages.py. Do not edit by hand. -->",
               "<!-- SCRIPT:END -->"),
    "toolbar": ("<!-- TOOLBAR:START - generated by build_pages.py. Do not edit by hand. -->",
                "<!-- TOOLBAR:END -->"),
    "toggle": ("<!-- TOGGLE:START - generated by build_pages.py. Do not edit by hand. -->",
               "<!-- TOGGLE:END -->"),
}

SELECTORS = [":root", 'html[data-theme="dark"]']
BLOCK_RE = {
    ":root": re.compile(r"(?<![\w-]):root\s*\{[^{}]*\}", re.S),
    'html[data-theme="dark"]': re.compile(r'html\[data-theme="dark"\]\s*\{[^{}]*\}', re.S),
}
STYLE_RE = re.compile(r"<style>(.*?)</style>", re.S)
TOKEN_RE = re.compile(r"(--[a-z0-9-]+)\s*:\s*([^;]+);")

# Selectors theme.css owns. Local copies are stripped so the shared file wins.
OWNED_SELECTORS = [".toolbar", ".quiet-btn", ".quiet-btn:hover",
                   ".quiet-btn:focus-visible", ".quiet-btn svg"]

# Default is light. The OS preference is deliberately not consulted: this is a
# customer-facing reference site and a predictable first paint matters more.
# The "js" class gates progressive-enhancement-only styles (the index card
# clamp), so it must be set here, before first paint.
HEAD_SCRIPT = """<script>
  (() => {
    const param = new URLSearchParams(window.location.search).get("scoutTheme");
    let stored = null;
    try { stored = localStorage.getItem("resourcesTheme"); } catch (err) { /* private mode */ }
    document.documentElement.setAttribute("data-theme", param || stored || "light");
    document.documentElement.classList.add("js");
  })();
</script>"""

SUN = ('<svg class="icon-to-light" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
       'stroke-width="2" stroke-linecap="round" aria-hidden="true">'
       '<circle cx="12" cy="12" r="4.2"/><path d="M12 2.6v2.2M12 19.2v2.2M4.2 12H2M22 12h-2.2'
       'M6.5 6.5 4.9 4.9M19.1 19.1l-1.6-1.6M17.5 6.5l1.6-1.6M4.9 19.1l1.6-1.6"/></svg>')
MOON = ('<svg class="icon-to-dark" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
        'stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
        '<path d="M20.5 14.3A8.5 8.5 0 0 1 9.7 3.5a8.5 8.5 0 1 0 10.8 10.8z"/></svg>')
PRINTER = ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" '
           'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
           '<path d="M6 9V3h12v6"/><path d="M6 18H4.5A1.5 1.5 0 0 1 3 16.5v-5A1.5 1.5 0 0 1 '
           '4.5 10h15a1.5 1.5 0 0 1 1.5 1.5v5a1.5 1.5 0 0 1-1.5 1.5H18"/>'
           '<path d="M6 14h12v7H6z"/></svg>')

THEME_TOGGLE = (f'<button class="quiet-btn icon-only" id="themeToggle" type="button" '
                f'aria-label="Switch color theme" title="Switch theme">{SUN}{MOON}</button>')
PRINT_BUTTON = (f'<button class="quiet-btn" id="printBtn" type="button">{PRINTER}'
                f'<span class="btn-text">Print / Save as PDF</span></button>')

TOOLBAR = f"""<div class="toolbar">
    {THEME_TOGGLE}
    {PRINT_BUTTON}
  </div>"""

TOGGLE_SCRIPT = """<script>
  (() => {
    const root = document.documentElement;
    const toggle = document.getElementById("themeToggle");
    if (toggle) {
      toggle.addEventListener("click", () => {
        const next = root.getAttribute("data-theme") === "dark" ? "light" : "dark";
        root.setAttribute("data-theme", next);
        try { localStorage.setItem("resourcesTheme", next); } catch (err) { /* private mode */ }
      });
    }
    const printBtn = document.getElementById("printBtn");
    if (printBtn) printBtn.addEventListener("click", () => window.print());
  })();
</script>"""


def region(name, body):
    start, end = M[name]
    return f"{start}\n{body}\n{end}"


def region_re(name):
    start, end = M[name]
    return re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)


def load_theme():
    css = THEME.read_text(encoding="utf-8")
    blocks, owned = {}, set()
    for sel in SELECTORS:
        m = BLOCK_RE[sel].search(css)
        if not m:
            sys.exit(f"theme.css is missing a {sel} block")
        blocks[sel] = m.group(0).strip()
        owned |= {k for k, _ in TOKEN_RE.findall(m.group(0))}
    chrome = css.split(blocks['html[data-theme="dark"]'], 1)[1].strip()
    return blocks, owned, chrome


def extras_of(block_text, owned):
    return [(k, " ".join(v.split())) for k, v in TOKEN_RE.findall(block_text) if k not in owned]


def render_block(canonical, extras):
    if not extras:
        return canonical
    lines = [canonical.rstrip()[:-1].rstrip(), "  /* page-specific */"]
    lines += [f"  {k}: {v};" for k, v in extras]
    lines.append("}")
    return "\n".join(lines)


def strip_owned_rules(css):
    """Remove local copies of selectors theme.css owns."""
    for sel in OWNED_SELECTORS:
        pattern = re.compile(r"(?<![\w.:-])" + re.escape(sel) + r"\s*\{[^{}]*\}\s*", re.S)
        css = pattern.sub("", css)
    return css


def apply_theme_region(text, theme_blocks, owned, chrome):
    rx = region_re("theme")
    existing = rx.search(text)
    source = existing.group(0) if existing else text

    extras = {}
    for sel in SELECTORS:
        m = BLOCK_RE[sel].search(source)
        if m:
            extras[sel] = extras_of(m.group(0), owned)

    body = "\n\n".join(render_block(theme_blocks[sel], extras.get(sel, [])) for sel in SELECTORS)
    body += "\n\n" + chrome
    new_region = region("theme", body)

    if existing:
        return text[:existing.start()] + new_region + text[existing.end():]

    spans = sorted((m.start(), m.end())
                   for m in (BLOCK_RE[s].search(text) for s in SELECTORS) if m)
    if not spans:
        return text
    out, cursor = [], 0
    for i, (s, e) in enumerate(spans):
        out.append(text[cursor:s])
        if i == 0:
            out.append(new_region)
        cursor = e
    out.append(text[cursor:])
    return re.sub(r"\n[ \t]*\n[ \t]*\n+", "\n\n", "".join(out))


def apply_simple_region(text, name, body, legacy_re):
    """Replace an existing managed region, else the legacy markup it supersedes."""
    rx = region_re(name)
    new_region = region(name, body)
    existing = rx.search(text)
    if existing:
        return text[:existing.start()] + new_region + text[existing.end():]
    m = legacy_re.search(text) if legacy_re else None
    if m:
        return text[:m.start()] + new_region + text[m.end():]
    return text


LEGACY_SCRIPT = re.compile(
    r"<script>\s*\(\(\)\s*=>\s*\{[^<]*?scoutTheme[^<]*?\}\)\(\);\s*</script>", re.S)
LEGACY_TOOLBAR = re.compile(r'<div class="toolbar">.*?</div>', re.S)
LEGACY_PRINT_WIRE = re.compile(
    r'<script>\s*document\.getElementById\("printBtn"\)\.addEventListener\('
    r'"click",\s*\(\)\s*=>\s*window\.print\(\)\);\s*</script>', re.S)


def process(path, theme_blocks, owned, chrome):
    original = path.read_text(encoding="utf-8")
    style = STYLE_RE.search(original)
    if not style or "--cp-" not in style.group(1):
        return None

    text = apply_theme_region(original, theme_blocks, owned, chrome)

    # Strip local copies of owned selectors, but only outside the managed region.
    rx = region_re("theme")
    m = rx.search(text)
    if m:
        head, managed, tail = text[:m.start()], m.group(0), text[m.end():]
        style_in_tail = tail.split("</style>", 1)
        if len(style_in_tail) == 2:
            tail = strip_owned_rules(style_in_tail[0]) + "</style>" + style_in_tail[1]
        text = head + managed + tail

    text = apply_simple_region(text, "script", HEAD_SCRIPT, LEGACY_SCRIPT)
    text = apply_simple_region(text, "toolbar", TOOLBAR, LEGACY_TOOLBAR)

    if "printBtn" in text or "themeToggle" in text:
        if region_re("toggle").search(text) or LEGACY_PRINT_WIRE.search(text):
            text = apply_simple_region(text, "toggle", TOGGLE_SCRIPT, LEGACY_PRINT_WIRE)
        elif "</body>" in text:
            text = text.replace("</body>", region("toggle", TOGGLE_SCRIPT) + "\n</body>", 1)

    if text == original:
        return (False, 0)
    path.write_text(text, encoding="utf-8")
    return (True, sum(len(v) for v in
                      (extras_of(BLOCK_RE[s].search(text).group(0), owned)
                       for s in SELECTORS if BLOCK_RE[s].search(text))))


def main():
    theme_blocks, owned, chrome = load_theme()
    targets = [p for p in sorted(ROOT.glob("*.html"))
               if p.name not in SKIP and p.name != GENERATED_INDEX]

    touched = changed = 0
    for path in targets:
        result = process(path, theme_blocks, owned, chrome)
        if result is None:
            continue
        written, extras = result
        touched += 1
        if written:
            changed += 1
            note = f" (+{extras} page-specific)" if extras else ""
            print(f"  {path.name:<62} rewritten{note}")

    print(f"\nTheme present in {touched} pages; {changed} rewritten this run")
    print(f"Tokens owned by theme.css: {len(owned)}")

    sys.path.insert(0, str(ROOT))
    import build_index
    build_index.main()


if __name__ == "__main__":
    main()
